import type { Metadata } from "next";
 import "./globals.css";
import DecorativeLines from "@/components/admin/DecorativeLines";

export const metadata: Metadata = {
  title: "Abdalraheem Ghannam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen pt-12 bg-gradient-to-br from-[#000814] via-[#001D3D] to-[#003566] relative">
        {/* حاوية المحتوى */}
        <div className="relative w-full max-w-7xl mx-auto px-4">
          {children}
        </div>

 <DecorativeLines/>
      </body>
    </html>
  );
}
